### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by hiro1129-2mc** [hiro1129-2mc/findvinyl#122]
## 各種情報
サービス名 : VinylLog
サービスURL : https://vinyllog-233013640988.herokuapp.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] 機能名
- [x] アカウント登録機能
- [x] ログイン機能
- [ ] プロフィール機能
- [x] マイページ機能
- [x] レコード検索機能
- [ ] おすすめのレコード表示機能
- [x] コレクション登録機能
- [x] コレクション検索機能
- [x] コレクションランダム表示機能
- [x] ほしい物リスト登録機能
- [x] ほしい物リスト検索機能
- [x] 聴いたレコードを記録する機能

## READMEレビュー時から変更した機能
- プロフィール機能(名前・メールアドレス・パスワード変更/アイコンアップロード機能)は本リリース時に回すことにさせていただきたいです。
- 本リリース時に予定していたアイテムのタグ付け機能は既に実装しました。
- おすすめのレコード表示機能は実装をやめました。
- レコード検索機能は現在本番環境DBへの初期データのインポートに時間がかかっており、アーティスト検索しかできませんが、データのインポートが済み次第、リリース検索もできるようになる予定です。
- READMEレビュー時はFly.ioにデプロイ予定でしたが、Herokuに変更いたしました。
- また、以下の不具合がありますが、今後修正いたします。

  - 記録作成・編集画面に遷移後、一度リロードしないとJavaScriptが発火しない
  - マイページのコレクションランダム表示のswiperが動かない

お手数をお掛けいたしますが、ご確認お願いいたします。

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます。
「聴いたレコードを記録する機能」で質問します。
レコード検索とありますが、これはどのような操作を行うとレコード検索ができるのかを教えてください。
また聴いたレコードという文字列がありますが、どうやって登録ができるかを教えてください。

![image](https://github.com/hiro1129-2mc/findvinyl/assets/61481161/283792e9-5b69-4a88-bcc1-3e4ce3457480)

**Comment by hiro1129-2mc** [comment]
ご確認ありがとうございます。
レコード検索はコレクションを作成画面・欲しいもの作成画面からレコードを登録し、レコード検索フォームに登録したレコードのタイトルかアーティスト名を入力すると候補が出ます。

[![Image from Gyazo](https://i.gyazo.com/f58f9026a829cfa96fc7e96cf9e140c1.png)](https://gyazo.com/f58f9026a829cfa96fc7e96cf9e140c1)

表示されたレコードの候補の横にある+ボタンを押すと、聞いたレコード欄に追加されます。

[![Image from Gyazo](https://i.gyazo.com/f35b0d19fa21e599e310f78c1d6f84e1.png)](https://gyazo.com/f35b0d19fa21e599e310f78c1d6f84e1)

説明不足で申し訳ありません。
お手数をお掛けいたしますが、再度ご確認お願いいたします。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
